/*
Copyright (c) 2020 Mandelsoft. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/mandelsoft/k8sbridge/pkg/apis/kubelink/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKubeLinks implements KubeLinkInterface
type FakeKubeLinks struct {
	Fake *FakeKubelinkV1alpha1
	ns   string
}

var kubelinksResource = schema.GroupVersionResource{Group: "kubelink.mandelsoft.org", Version: "v1alpha1", Resource: "kubelinks"}

var kubelinksKind = schema.GroupVersionKind{Group: "kubelink.mandelsoft.org", Version: "v1alpha1", Kind: "KubeLink"}

// Get takes name of the kubeLink, and returns the corresponding kubeLink object, and an error if there is any.
func (c *FakeKubeLinks) Get(name string, options v1.GetOptions) (result *v1alpha1.KubeLink, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(kubelinksResource, c.ns, name), &v1alpha1.KubeLink{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KubeLink), err
}

// List takes label and field selectors, and returns the list of KubeLinks that match those selectors.
func (c *FakeKubeLinks) List(opts v1.ListOptions) (result *v1alpha1.KubeLinkList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(kubelinksResource, kubelinksKind, c.ns, opts), &v1alpha1.KubeLinkList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.KubeLinkList{ListMeta: obj.(*v1alpha1.KubeLinkList).ListMeta}
	for _, item := range obj.(*v1alpha1.KubeLinkList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested kubeLinks.
func (c *FakeKubeLinks) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(kubelinksResource, c.ns, opts))

}

// Create takes the representation of a kubeLink and creates it.  Returns the server's representation of the kubeLink, and an error, if there is any.
func (c *FakeKubeLinks) Create(kubeLink *v1alpha1.KubeLink) (result *v1alpha1.KubeLink, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(kubelinksResource, c.ns, kubeLink), &v1alpha1.KubeLink{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KubeLink), err
}

// Update takes the representation of a kubeLink and updates it. Returns the server's representation of the kubeLink, and an error, if there is any.
func (c *FakeKubeLinks) Update(kubeLink *v1alpha1.KubeLink) (result *v1alpha1.KubeLink, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(kubelinksResource, c.ns, kubeLink), &v1alpha1.KubeLink{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KubeLink), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeKubeLinks) UpdateStatus(kubeLink *v1alpha1.KubeLink) (*v1alpha1.KubeLink, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(kubelinksResource, "status", c.ns, kubeLink), &v1alpha1.KubeLink{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KubeLink), err
}

// Delete takes name of the kubeLink and deletes it. Returns an error if one occurs.
func (c *FakeKubeLinks) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(kubelinksResource, c.ns, name), &v1alpha1.KubeLink{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKubeLinks) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(kubelinksResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.KubeLinkList{})
	return err
}

// Patch applies the patch and returns the patched kubeLink.
func (c *FakeKubeLinks) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.KubeLink, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(kubelinksResource, c.ns, name, pt, data, subresources...), &v1alpha1.KubeLink{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KubeLink), err
}
