/*
Copyright (c) 2020 Mandelsoft. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/mandelsoft/kubelink/pkg/apis/kubelink/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMeshServices implements MeshServiceInterface
type FakeMeshServices struct {
	Fake *FakeKubelinkV1alpha1
	ns   string
}

var meshservicesResource = schema.GroupVersionResource{Group: "kubelink.mandelsoft.org", Version: "v1alpha1", Resource: "meshservices"}

var meshservicesKind = schema.GroupVersionKind{Group: "kubelink.mandelsoft.org", Version: "v1alpha1", Kind: "MeshService"}

// Get takes name of the meshService, and returns the corresponding meshService object, and an error if there is any.
func (c *FakeMeshServices) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.MeshService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(meshservicesResource, c.ns, name), &v1alpha1.MeshService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MeshService), err
}

// List takes label and field selectors, and returns the list of MeshServices that match those selectors.
func (c *FakeMeshServices) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MeshServiceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(meshservicesResource, meshservicesKind, c.ns, opts), &v1alpha1.MeshServiceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.MeshServiceList{ListMeta: obj.(*v1alpha1.MeshServiceList).ListMeta}
	for _, item := range obj.(*v1alpha1.MeshServiceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested meshServices.
func (c *FakeMeshServices) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(meshservicesResource, c.ns, opts))

}

// Create takes the representation of a meshService and creates it.  Returns the server's representation of the meshService, and an error, if there is any.
func (c *FakeMeshServices) Create(ctx context.Context, meshService *v1alpha1.MeshService, opts v1.CreateOptions) (result *v1alpha1.MeshService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(meshservicesResource, c.ns, meshService), &v1alpha1.MeshService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MeshService), err
}

// Update takes the representation of a meshService and updates it. Returns the server's representation of the meshService, and an error, if there is any.
func (c *FakeMeshServices) Update(ctx context.Context, meshService *v1alpha1.MeshService, opts v1.UpdateOptions) (result *v1alpha1.MeshService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(meshservicesResource, c.ns, meshService), &v1alpha1.MeshService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MeshService), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMeshServices) UpdateStatus(ctx context.Context, meshService *v1alpha1.MeshService, opts v1.UpdateOptions) (*v1alpha1.MeshService, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(meshservicesResource, "status", c.ns, meshService), &v1alpha1.MeshService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MeshService), err
}

// Delete takes name of the meshService and deletes it. Returns an error if one occurs.
func (c *FakeMeshServices) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(meshservicesResource, c.ns, name), &v1alpha1.MeshService{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMeshServices) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(meshservicesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.MeshServiceList{})
	return err
}

// Patch applies the patch and returns the patched meshService.
func (c *FakeMeshServices) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MeshService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(meshservicesResource, c.ns, name, pt, data, subresources...), &v1alpha1.MeshService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MeshService), err
}
