/*
Copyright (c) 2020 Mandelsoft. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/mandelsoft/kubelink/pkg/apis/kubelink/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMeshMembers implements MeshMemberInterface
type FakeMeshMembers struct {
	Fake *FakeKubelinkV1alpha1
	ns   string
}

var meshmembersResource = schema.GroupVersionResource{Group: "kubelink.mandelsoft.org", Version: "v1alpha1", Resource: "meshmembers"}

var meshmembersKind = schema.GroupVersionKind{Group: "kubelink.mandelsoft.org", Version: "v1alpha1", Kind: "MeshMember"}

// Get takes name of the meshMember, and returns the corresponding meshMember object, and an error if there is any.
func (c *FakeMeshMembers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.MeshMember, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(meshmembersResource, c.ns, name), &v1alpha1.MeshMember{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MeshMember), err
}

// List takes label and field selectors, and returns the list of MeshMembers that match those selectors.
func (c *FakeMeshMembers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MeshMemberList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(meshmembersResource, meshmembersKind, c.ns, opts), &v1alpha1.MeshMemberList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.MeshMemberList{ListMeta: obj.(*v1alpha1.MeshMemberList).ListMeta}
	for _, item := range obj.(*v1alpha1.MeshMemberList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested meshMembers.
func (c *FakeMeshMembers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(meshmembersResource, c.ns, opts))

}

// Create takes the representation of a meshMember and creates it.  Returns the server's representation of the meshMember, and an error, if there is any.
func (c *FakeMeshMembers) Create(ctx context.Context, meshMember *v1alpha1.MeshMember, opts v1.CreateOptions) (result *v1alpha1.MeshMember, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(meshmembersResource, c.ns, meshMember), &v1alpha1.MeshMember{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MeshMember), err
}

// Update takes the representation of a meshMember and updates it. Returns the server's representation of the meshMember, and an error, if there is any.
func (c *FakeMeshMembers) Update(ctx context.Context, meshMember *v1alpha1.MeshMember, opts v1.UpdateOptions) (result *v1alpha1.MeshMember, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(meshmembersResource, c.ns, meshMember), &v1alpha1.MeshMember{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MeshMember), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMeshMembers) UpdateStatus(ctx context.Context, meshMember *v1alpha1.MeshMember, opts v1.UpdateOptions) (*v1alpha1.MeshMember, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(meshmembersResource, "status", c.ns, meshMember), &v1alpha1.MeshMember{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MeshMember), err
}

// Delete takes name of the meshMember and deletes it. Returns an error if one occurs.
func (c *FakeMeshMembers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(meshmembersResource, c.ns, name), &v1alpha1.MeshMember{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMeshMembers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(meshmembersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.MeshMemberList{})
	return err
}

// Patch applies the patch and returns the patched meshMember.
func (c *FakeMeshMembers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MeshMember, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(meshmembersResource, c.ns, name, pt, data, subresources...), &v1alpha1.MeshMember{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MeshMember), err
}
