#!/bin/bash
#
# Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

rm -f $GOPATH/bin/*-gen

CURRENT_DIR=$(dirname $0)
PROJECT_ROOT="${CURRENT_DIR}"/..

source "$PROJECT_ROOT/build/settings.src"

VPATHS="$PKGPATH/pkg/apis/$APINAME"
for v in $(IFS=,; echo $APIVERSION); do
  VPATHS="$VPATHS,$PKGPATH/pkg/apis/$APINAME/$v"
done

bash "${PROJECT_ROOT}"/vendor/k8s.io/code-generator/generate-internal-groups.sh \
  deepcopy,client,informer,lister,defaulter \
  $PKGPATH/pkg/client/$APINAME \
  $PKGPATH/pkg/apis \
  $PKGPATH/pkg/apis \
  "$APINAME:$APIVERSION" \
  --go-header-file "$(dirname $0)/LICENSE_BOILERPLATE.txt"

bash "${PROJECT_ROOT}"/vendor/k8s.io/code-generator/generate-internal-groups.sh \
  conversion \
  $PKGPATH/pkg/client/$APINAME \
  $PKGPATH/pkg/apis \
  $PKGPATH/pkg/apis \
  "$APINAME:$APIVERSION" \
  --extra-peer-dirs=$VPATHS,k8s.io/apimachinery/pkg/apis/meta/v1,k8s.io/apimachinery/pkg/conversion,k8s.io/apimachinery/pkg/runtime \
  --go-header-file "$(dirname $0)/LICENSE_BOILERPLATE.txt"