
namespace: kubelink
runmode: wireguard
podmode: true
image:   ghcr.io/mandelsoft/kubelink
version: latest

meshName: kubelink
meshCIDR: 192.168.0.0/24

globalDNS:
  member: kubelink1
  ip: (( min_ip(members[member].serviceCIDR) + 12 ))

#
# default unshared cidrs for mesh members
# can be explicitly specified in members
#
nodeCIDR: 10.250.0.0/16
podCIDR:  100.96.0.0/11

#
# full mesh members (generate manifests)
# with connected service subnets
# support.members is a utility function that generates standard members based on
# a settings object by successive usage of ip ranges name enumerated names
#
members: (( support.members(settings) ))

rollkeys: false

#
# addtitional foreign mesh member links
#
external:
  - name: aws20
    clusterAddress: (( min_ip(meshCIDR) + 20 ))
    egress:
    - (( min_ip(meshCIDR) + 101 ))
    endpoint:  18.196.188.244:51820
    publicKey: JexxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtUY=

#
# just generate n members according to a dedicated pattern
# instead of specifying a manual list in field members above.
# This setting is used by the function suppotz.members above.
#
settings:
  <<: (( &temporary ))
  # number of members to generate
  members: 2
  # basename for member names
  basename: kubelink
  # basedomain for dns names for clusters
  basedomain: ringdev.shoot.dev.k8s-hana.ondemand.com
  # ip range to select member service ip ranges from
  meshServiceRange: 100.64.0.0/16
  # number of service nets to split service range into
  meshServiceNetCount: 16
  # start ip to use for members of mesh network
  meshStartIP: 11
