/*
Copyright (c) 2020 Mandelsoft. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	kubelinkv1alpha1 "github.com/mandelsoft/kubelink/pkg/apis/kubelink/v1alpha1"
	versioned "github.com/mandelsoft/kubelink/pkg/client/kubelink/clientset/versioned"
	internalinterfaces "github.com/mandelsoft/kubelink/pkg/client/kubelink/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/mandelsoft/kubelink/pkg/client/kubelink/listers/kubelink/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// MeshMemberInformer provides access to a shared informer and lister for
// MeshMembers.
type MeshMemberInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.MeshMemberLister
}

type meshMemberInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewMeshMemberInformer constructs a new informer for MeshMember type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewMeshMemberInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredMeshMemberInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredMeshMemberInformer constructs a new informer for MeshMember type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredMeshMemberInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KubelinkV1alpha1().MeshMembers(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KubelinkV1alpha1().MeshMembers(namespace).Watch(context.TODO(), options)
			},
		},
		&kubelinkv1alpha1.MeshMember{},
		resyncPeriod,
		indexers,
	)
}

func (f *meshMemberInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredMeshMemberInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *meshMemberInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&kubelinkv1alpha1.MeshMember{}, f.defaultInformer)
}

func (f *meshMemberInformer) Lister() v1alpha1.MeshMemberLister {
	return v1alpha1.NewMeshMemberLister(f.Informer().GetIndexer())
}
